### ISSUE TITLE
Potential editorial mistake in `README.md`

### ISSUE THREAD

**Issue by LNow** [jcnelson/nftree#2]
Hey @jcnelson!
I like the idea of using Merkel tree to pre-mint all NFT's in collection. :clap: 

In `README.md` file you mentioned `instantiate-nftree` function: 
> Once the NFT creator has the outputted NFT descriptor, they can call (instantiate-nftree) with it:

There is no such function in the project source files, and almost identical sentence can be found few lines above, so I think it's just an editorial mistake.

**Comment by jcnelson** [comment]
Yup; fixed.
