### ISSUE TITLE
`register-nftree` and `register-contract-nftree` allows to register same tree multiple times.

### ISSUE THREAD

**Issue by LNow** [jcnelson/nftree#3]
Both functions `register-nftree` and `register-contract-nftree` don't check if provided tree root has been already registered or not.
I can imagine a situation in which artist would like to release same collection more than once, but I would say it should be always done using separate, unique tree.

**Comment by jcnelson** [comment]
That's fine -- tree uniqueness isn't a design goal.  Also, the NFTs (including the NFTrees) will have different NFT IDs, so even if this does happen and causes problems, they can be worked around simply by inspecting the IDs.
